// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecurityMonitor.Infrastructure.Persistence;

#nullable disable

namespace SecurityMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721174832_CreateDevicesGroupsAndZonesTables")]
    partial class CreateDevicesGroupsAndZonesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.DeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceState")
                        .HasColumnType("integer")
                        .HasColumnName("device_state");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("device_type");

                    b.Property<int>("SecuritySchemeId")
                        .HasColumnType("integer")
                        .HasColumnName("security_scheme_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("SecuritySchemeId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_security_scheme_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_groups_device_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.SecuritySchemeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_security_schemes");

                    b.ToTable("security_schemes", (string)null);
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.ZoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_zones_device_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_zones_group_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.DeviceEntity", b =>
                {
                    b.HasOne("SecurityMonitor.Infrastructure.Persistence.Entities.SecuritySchemeEntity", "SecurityScheme")
                        .WithOne("Device")
                        .HasForeignKey("SecurityMonitor.Infrastructure.Persistence.Entities.DeviceEntity", "SecuritySchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_security_schemes_security_scheme_id");

                    b.Navigation("SecurityScheme");
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.GroupEntity", b =>
                {
                    b.HasOne("SecurityMonitor.Infrastructure.Persistence.Entities.DeviceEntity", "Device")
                        .WithMany("Groups")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.ZoneEntity", b =>
                {
                    b.HasOne("SecurityMonitor.Infrastructure.Persistence.Entities.DeviceEntity", "Device")
                        .WithMany("Zones")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zones_devices_device_id");

                    b.HasOne("SecurityMonitor.Infrastructure.Persistence.Entities.GroupEntity", "Group")
                        .WithMany("Zones")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_zones_groups_group_id");

                    b.Navigation("Device");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.DeviceEntity", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.GroupEntity", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SecurityMonitor.Infrastructure.Persistence.Entities.SecuritySchemeEntity", b =>
                {
                    b.Navigation("Device")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
